# Generated by Django 5.0.6 on 2024-06-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_categoria_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
