# Generated by Django 5.0.6 on 2024-06-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_alter_producto_tamaño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(choices=[('Grande', 'grande'), ('Pequeño', 'pequeño')], default='Grande', max_length=10),
        ),
    ]
